version: '3.7'
services:
    pingservice:
        build:
            context: .
            dockerfile: "Dockerfile_pingService"
        ports:
            -  "8080:8080"
    receiverservice:
         build:
            context: .
            dockerfile: "Dockerfile_receiverService"
         ports:
            -  "8081:8080"
    test:
        build:
            context: .
            dockerfile: "Dockerfile_test"
